name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.name }}

      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      #     - name: Build the Docker image
      #       run: docker build -t chunwarayut/psd-meback-bot:latest .

      - name: Push to Docker Hub RN
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: chunwarayut/psd-meback-bot:latest

      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          private_key: ${{ secrets.SSH_KEY }}
          command: docker pull chunwarayut/psd-meback-bot:latest && docker stop psd-meback-bot && docker rm psd-meback-bot && docker run --name psd-meback-bot --restart=always -d chunwarayut/psd-meback-bot
